#run with python 3 readStats.py

#For a file containing fastq file read counts (e.g., generated by script countReads_R1.sh), calculate and print the total number of reads across all samples and the average, min and max number of reads per sample

fhand=open('readCounts_R1.txt')
counts=list()
for line in fhand:
    line=line.rstrip()
    words=line.split()
    count=words[1]
    try:
        fcount=float(count)
    except:
        continue
    else:
        counts.append(fcount)
#double all numbers below to count R1+R2 reads, not just R1
print('Total:',(sum(counts)*2))
print('Average:',(sum(counts)*2)/len(counts))
print('Min:',(max(counts)*2))
print('Max:',(min(counts)*2))
